# Generated by Django 2.0.4 on 2018-05-21 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_name', models.CharField(max_length=200)),
                ('khmer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('japanese_name', models.CharField(blank=True, max_length=200)),
                ('nationality', models.CharField(max_length=50)),
                ('place_of_birth', models.CharField(max_length=200)),
                ('card_id', models.CharField(blank=True, max_length=100, null=True)),
                ('khmer_salary', models.FloatField(blank=True, default=150, max_length=10, null=True)),
                ('education', models.CharField(choices=[('Primary School', 'Primary School'), ('Secondary School', 'Secondary School'), ('High School', 'High School'), ('University', 'University'), ('Vocation School', 'Vocation Shool'), ('Traning School', 'Traning School')], max_length=200, null=True)),
                ('date_of_birth', models.DateField()),
                ('age', models.PositiveIntegerField(default=0)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=200)),
                ('state_of_healt', models.CharField(blank=True, max_length=20, null=True)),
                ('blood_type', models.CharField(blank=True, max_length=20, null=True)),
                ('vision', models.CharField(blank=True, max_length=50, null=True)),
                ('interest', models.CharField(blank=True, max_length=50, null=True)),
                ('year_of_experience', models.IntegerField(default=0, null=True)),
                ('married', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50)),
                ('position', models.CharField(blank=True, max_length=50, null=True)),
                ('behavior', models.CharField(blank=True, max_length=50)),
                ('went_to_japan', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50)),
                ('japanese_conversation', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50)),
                ('height', models.CharField(blank=True, max_length=50, null=True)),
                ('weight', models.CharField(blank=True, max_length=50, null=True)),
                ('current_address', models.CharField(max_length=200)),
                ('reason', models.CharField(choices=[('Increase Revenue', 'Increase Revenue'), ('Respect to parents', 'Respect to parents'), ('Improve Living', 'Improve Living'), ('Education', 'Education'), ('Other Reason', 'Other Reason')], max_length=255)),
                ('arrang_money', models.TextField(blank=True, max_length=255, null=True)),
                ('sending_company', models.CharField(choices=[('Company 168', 'Company 168'), ('Phnom Penh Thmey', 'Phnom Penh Thmey'), ('CL Supply Company', 'CL Supply COMPANY'), ('Other Company', 'Other Company')], max_length=200)),
                ('japanese_level', models.CharField(choices=[('level', 'level'), ('N5', 'N5'), ('N4', 'N4'), ('N3', 'N3'), ('N2', 'N2'), ('N1', 'N1')], max_length=50)),
                ('field_of_work', models.CharField(blank=True, max_length=50, null=True)),
                ('date_go_japan', models.DateField(blank=True, null=True)),
                ('prefecture', models.CharField(blank=True, max_length=50, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=50, null=True)),
                ('address_in_japan', models.CharField(max_length=200, null=True)),
                ('grammer_level', models.CharField(blank=True, max_length=200, null=True)),
                ('idiom_level', models.CharField(blank=True, max_length=200, null=True)),
                ('conversation_level', models.CharField(blank=True, max_length=200, null=True)),
                ('life_attitude', models.CharField(blank=True, max_length=200, null=True)),
                ('course_type', models.CharField(blank=True, max_length=100, null=True)),
                ('last_peroid_of_study', models.DateField(blank=True, null=True)),
                ('university_name', models.CharField(blank=True, max_length=200, null=True)),
                ('subject_name', models.CharField(blank=True, max_length=100, null=True)),
                ('teacher_name', models.CharField(blank=True, max_length=50, null=True)),
                ('book_type', models.CharField(blank=True, max_length=50, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('admin_name', models.CharField(blank=True, max_length=50, null=True)),
                ('email_address', models.EmailField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fujiyama',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='studentpages.Student')),
                ('entry_date', models.DateField(null=True)),
                ('score', models.FloatField(default=0)),
                ('player_learn_detail', models.CharField(max_length=200, null=True)),
                ('correct_answer', models.IntegerField(default=0)),
                ('duration', models.DurationField()),
                ('email', models.EmailField(max_length=250, null=True)),
                ('incorrect_answer', models.IntegerField(default=0)),
                ('login_source', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=200)),
            ],
        ),
    ]
